# dockerfile per il client
FROM node:20-alpine

# Crea e imposta la directory di lavoro
WORKDIR /app

# Copia i file del package e installa le dipendenze
COPY package*.json ./
RUN npm install

# Copia il resto dell'app
COPY . .

# Espone la porta su cui il client ascolta
EXPOSE 5173

# Comando per avviare il client
CMD [ "npm", "run", "dev" ]
