
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: greenvisa-db
    ports:
      - "5432:5432"
    volumes:
      - greenvisa_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d green-visa" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb
    container_name: greenvisa-pgweb
    environment:
      PGW_DB_HOST: db
      PGW_DB_PORT: 5432
      PGW_DB_USER: admin
      PGW_DB_PASS: pass123
      PGW_DB_NAME: green-visa
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

volumes:
  greenvisa_postgres_data: