services:
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    command: ["node", "server"]
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - NODE_ENV=production
    volumes:
      - ./server/uploaded_img:/app/uploaded_img
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: dockerfile.database.prod
    ports:
      - "5432:5432"
    volumes:
      - green-visa-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d green-visa" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  green-visa-db:
