# dockerfile per il server
FROM node:20-alpine

# Crea e imposta la directory di lavoro
WORKDIR /app

# Copia i file del package e installa le dipendenze
COPY package*.json ./
RUN npm install

# Copia il resto dell'app
COPY . .

# Espone la porta su cui il server ascolta
EXPOSE 8080


# Comando per avviare il server
CMD [ "npm", "run", "dev" ]


